apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sql-schema-postgresql-credentials
  namespace: zuno-data
  labels:
    zuno.io/managed-by: zuno-ansible
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sql-schema-postgresql-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgresql/app
        property: username
    - secretKey: password
      remoteRef:
        key: postgresql/app
        property: password
