#!/usr/bin/env python3
"""ADR-0119 scaffolding tool: generate a new MCP server from the
`components/mcp-servers/confluence` template (real `mcp` SDK server,
streamable-HTTP transport, `GatewayTokenMiddleware`, `/healthz`,
`TransportSecuritySettings`) instead of hand-copying an existing server
directory-by-directory.

Generates:
  - components/mcp-servers/<name>/{server.py,requirements.txt,Dockerfile,
    README.md,tests/test_mcp_protocol.py}
  - gitops/charts/mcp-<name>/{Chart.yaml,values.yaml,templates/*}
  - gitops/apps/mcp-<name>/{application-d0.yaml,application-d1.yaml}

The generated server.py has one placeholder tool (`example_tool`) and a
single default credential (`<NAME>_API_TOKEN`, one Vault path,
`service-identity` auth mode) - the common case. A server needing more
than one credential/Vault path (e.g. a multi-provider integration) or a
different auth mode must hand-edit the generated `server.py`/
`externalsecret.yaml`/`deployment.yaml` afterward; this script produces a
correct, conformant starting point, not a no-edit final artifact.

Never overwrites an existing file - run once per new server, then edit by
hand. Re-run is safe (it will refuse and list what already exists).

Run from the repository root:

    python3 platform/scaffolding/new_mcp_server.py <name> \\
        --description "One-line description of what this server integrates with"
"""
from __future__ import annotations

import argparse
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]


def _pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("-"))


def _upper_snake(name: str) -> str:
    return name.replace("-", "_").upper()


def _allowed_hosts(name: str) -> str:
    svc = f"{name}-mcp"
    return (
        f"{svc}.zuno-ai-run.svc:8000,"
        f"{svc}.zuno-ai-run.svc.cluster.local:8000,"
        f"{svc}:8000,localhost:8000,127.0.0.1:8000"
    )


def _server_py(name: str, description: str) -> str:
    upper = _upper_snake(name)
    hosts = _allowed_hosts(name)
    return f'''"""{name} MCP server (ADR-0119 scaffold - {description}).

Generated by platform/scaffolding/new_mcp_server.py from the
components/mcp-servers/confluence template: a real, standards-compliant
MCP server (the `mcp` SDK's `MCPServer`, streamable-HTTP transport,
mounted at /mcp), gateway-token-authenticated (ADR-0037).

Replace `example_tool` below with this integration's real tools, and give
the capabilities canonical `<domain>.<resource>.<verb>` IDs (ADR-0116) in
platform/bindings/tools/tool-bindings.yaml + policies/tools/tool-policy.yaml.

Authentication mode: `service-identity` (ADR-0208) by default - one shared
technical credential ({upper}_API_TOKEN), sourced from an `ExternalSecret`
resolving `zuno/{name}/technical` (never hardcoded, ADR-0024). If this
integration needs more than one credential/Vault path, or a different
auth mode, edit this file, gitops/charts/mcp-{name}/templates/
externalsecret.yaml and deployment.yaml together - the generated single-
credential shape is a starting point, not a hard constraint.

    POST /mcp    - real MCP streamable-HTTP transport (initialize,
                   tools/list, tools/call)
    GET /healthz -> 200 once {upper}_API_TOKEN is configured. Deliberately
                   does NOT make a live call to the backend on every probe
                   - a Kubernetes liveness/readiness probe firing every
                   ~10-15s against a real external API would be a
                   needless, avoidable load/quota cost.
"""
from __future__ import annotations

import hmac
import os
from contextlib import asynccontextmanager
from typing import Any, Dict

from fastapi import FastAPI
from mcp.server.mcpserver import MCPServer
from mcp.server.transport_security import TransportSecuritySettings
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.types import ASGIApp

{upper}_API_TOKEN = os.getenv("{upper}_API_TOKEN", "")

# ADR-0037: required, not optional - this server has no purpose other than
# serving the gateway (same reasoning as sales-db/server.py).
GATEWAY_WORKLOAD_TOKEN = os.getenv("MCP_GATEWAY_WORKLOAD_TOKEN", "")


class {_pascal(name)}ConfigError(RuntimeError):
    pass


def _require_config() -> None:
    if not {upper}_API_TOKEN:
        raise {_pascal(name)}ConfigError(
            "{upper}_API_TOKEN is required (sourced from an ExternalSecret "
            "against secret/zuno/{name}/technical - never hardcoded, ADR-0024)"
        )


mcp_server = MCPServer(
    name="{name}",
    version="0.1.0",
    instructions="Replace with guidance on when an agent should use this tool.",
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # The mounted MCP sub-app's session manager needs the parent app's
    # lifespan to run its task group (same requirement as every other
    # server in components/mcp-servers/).
    async with mcp_server.session_manager.run():
        yield


app = FastAPI(title="{name} MCP server", lifespan=lifespan)


@app.get("/healthz")
async def healthz() -> Dict[str, str]:
    _require_config()
    return {{"status": "ok"}}


@mcp_server.tool()
async def example_tool(query: str) -> Dict[str, Any]:
    """Replace with a real tool. Remove this once at least one real tool exists."""
    _require_config()
    raise NotImplementedError("replace example_tool with a real capability")


class GatewayTokenMiddleware(BaseHTTPMiddleware):
    """ADR-0037 workload-identity check, ahead of any MCP protocol handling
    (identical pattern to every other server in components/mcp-servers/)."""

    async def dispatch(self, request: Request, call_next):
        caller_token = request.headers.get("x-zuno-gateway-token", "")
        if not GATEWAY_WORKLOAD_TOKEN or not hmac.compare_digest(caller_token, GATEWAY_WORKLOAD_TOKEN):
            return JSONResponse({{"detail": "missing or invalid X-Zuno-Gateway-Token"}}, status_code=401)
        return await call_next(request)


mcp_asgi_app: ASGIApp = mcp_server.streamable_http_app(
    streamable_http_path="/mcp",
    transport_security=TransportSecuritySettings(
        allowed_hosts=os.getenv(
            "MCP_ALLOWED_HOSTS",
            "{hosts}",
        ).split(","),
    ),
)
mcp_asgi_app.add_middleware(GatewayTokenMiddleware)
app.mount("/", mcp_asgi_app)
'''


def _requirements_txt() -> str:
    return "fastapi==0.141.1\nuvicorn[standard]==0.32.0\nhttpx==0.28.1\nmcp==2.0.0\n"


def _dockerfile() -> str:
    return '''# Defaults to the zuno-ai-build ImageStream mirror
# (ansible/roles/image_mirrors), not docker.io directly.
# .github/workflows/build-publish.yml (ADR-0115) overrides this ARG to the
# real docker.io image for GitHub-hosted runners.
ARG BASE_IMAGE=image-registry.openshift-image-registry.svc:5000/zuno-ai-build/python:3.12-slim
FROM ${BASE_IMAGE}

# ADR-0115: patch known HIGH CVEs baked into the upstream base image at
# build time - apt upgrade picks up patched OS packages, pip upgrade picks
# up patched pip/setuptools/wheel.
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/* && \\
    pip install --no-cache-dir --upgrade pip setuptools wheel

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY server.py .

EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
'''


def _readme_md(name: str, description: str) -> str:
    return f"""# MCP server: {name}

{description}

Generated by `platform/scaffolding/new_mcp_server.py` (ADR-0119) from the
`components/mcp-servers/confluence` template. Replace this README with a
real description once `example_tool` in `server.py` is replaced with real
capabilities, and give them canonical `<domain>.<resource>.<verb>` IDs
(ADR-0116) in `platform/bindings/tools/tool-bindings.yaml` and
`policies/tools/tool-policy.yaml`.

Transport: real MCP protocol (the official `mcp` Python SDK, streamable-
HTTP, mounted at `POST /mcp`). The gateway is the trust boundary - this
server does not re-validate the caller's end-user JWT; every `/mcp` call
must carry `X-Zuno-Gateway-Token`, a shared secret only the gateway holds.

**Authentication mode: `service-identity`** by default (ADR-0208) - one
shared technical credential sourced from an `ExternalSecret` resolving
`zuno/{name}/technical`. Edit `server.py`/the chart together if this
integration needs more than one credential or a different auth mode.

See `server.py`, `Dockerfile`, `requirements.txt`,
`tests/test_mcp_protocol.py`. Deployed by `gitops/charts/mcp-{name}` in
the `zuno-ai-run` namespace.
"""


def _test_mcp_protocol_py(name: str) -> str:
    upper = _upper_snake(name)
    return f'''"""ADR-0043/ADR-0119 protocol tests for the {name} MCP server: proves
this server's /mcp endpoint speaks real, standards-compliant MCP
streamable-HTTP - same style as every other server in
components/mcp-servers/. Extend TESTS below as real tools replace
`example_tool`.

Run from this directory:

    python3 tests/test_mcp_protocol.py
"""
from __future__ import annotations

import asyncio
import os
import sys

os.environ.setdefault("MCP_GATEWAY_WORKLOAD_TOKEN", "test-workload-token")
os.environ.setdefault("{upper}_API_TOKEN", "test-token")

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import httpx2  # noqa: E402
from httpx2 import ASGITransport  # noqa: E402
from mcp.client.session import ClientSession  # noqa: E402
from mcp.client.streamable_http import streamable_http_client  # noqa: E402

import server  # noqa: E402

BASE_URL = "http://localhost:8000"
GATEWAY_HEADERS = {{"X-Zuno-Gateway-Token": "test-workload-token"}}


async def _open_session(transport, headers):
    http_client = httpx2.AsyncClient(transport=transport, base_url=BASE_URL, headers=headers)
    return streamable_http_client(f"{{BASE_URL}}/mcp", http_client=http_client)


async def test_unauthenticated_call_rejected_before_any_protocol_handling(transport) -> None:
    async with httpx2.AsyncClient(transport=transport, base_url=BASE_URL) as client:
        resp = await client.post(
            "/mcp",
            json={{"jsonrpc": "2.0"}},
            headers={{"Accept": "application/json, text/event-stream", "Content-Type": "application/json"}},
        )
    assert resp.status_code == 401, f"expected 401 with no gateway token, got {{resp.status_code}}"


async def test_tools_list_reports_at_least_one_tool(transport) -> None:
    async with await _open_session(transport, GATEWAY_HEADERS) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.list_tools()
    assert len(result.tools) >= 1, "no tools registered - replace example_tool with a real one"


TESTS = [
    test_unauthenticated_call_rejected_before_any_protocol_handling,
    test_tools_list_reports_at_least_one_tool,
]


async def _run_all() -> int:
    transport = ASGITransport(app=server.app)
    lifespan_cm = server.app.router.lifespan_context(server.app)
    await lifespan_cm.__aenter__()

    failures = 0
    try:
        for test in TESTS:
            try:
                await test(transport)
            except Exception as exc:  # noqa: BLE001
                failures += 1
                print(f"FAIL {{test.__name__}}: {{exc}}")
            else:
                print(f"PASS {{test.__name__}}")
    finally:
        await lifespan_cm.__aexit__(None, None, None)
    return failures


def main() -> int:
    failures = asyncio.run(_run_all())
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _chart_yaml(name: str, description: str) -> str:
    return f"""apiVersion: v2
name: mcp-{name}
description: {description}
type: application
version: 0.1.0
appVersion: "0.1.0"
"""


def _values_yaml(name: str) -> str:
    return f"""# Must match mcp-gateway's binding registry entry (endpoint.default:
# http://{name}-mcp.zuno-ai-run.svc:8000) in
# platform/bindings/tools/tool-bindings.yaml.
namespace: zuno-ai-run

# Built by the "mcp" build component into zuno-ai-build's ImageStream, pulled
# cross-namespace into zuno-ai-run via the system:image-puller RoleBinding.
image:
  repository: image-registry.openshift-image-registry.svc:5000/zuno-ai-build/mcp-{name}
  tag: v0.1.0
  # Always, not IfNotPresent - with a mutable tag, IfNotPresent serves
  # whatever stale image the node cached, silently ignoring rebuilds.
  pullPolicy: Always

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# ADR-0208 service-identity: one shared technical identity for every
# caller (the gateway's own ADR-0011 intersection authorizes the actual
# caller before this identity is ever used). Extend with more entries
# under `data:` in templates/externalsecret.yaml if this integration
# needs more than one credential.
credentials:
  vaultPath: {name}/technical
  secretName: {name}-technical-credentials
  secretStoreName: vault-backend
  refreshInterval: 1h
"""


def _deployment_yaml(name: str) -> str:
    upper = _upper_snake(name)
    return f'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}-mcp
  namespace: {{{{ .Values.namespace }}}}
  labels:
    app.kubernetes.io/name: {name}-mcp
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    image.openshift.io/triggers: |-
      {{{{ include "mcp-{name}.imageTrigger" (dict "repository" .Values.image.repository "tag" .Values.image.tag "container" "{name}-mcp") }}}}
spec:
  replicas: {{{{ .Values.replicas }}}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {name}-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {name}-mcp
    spec:
      serviceAccountName: {name}-mcp
      priorityClassName: zuno-workload-default
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {name}-mcp
          image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag }}}}"
          imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: {upper}_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{{{ .Values.credentials.secretName }}}}
                  key: token
            - name: MCP_GATEWAY_WORKLOAD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mcp-gateway-workload-token
                  key: token
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{{{- toYaml .Values.resources | nindent 12 }}}}
      volumes:
        - name: tmp
          emptyDir: {{}}
'''


def _externalsecret_yaml(name: str) -> str:
    return f'''# ADR-0024/ADR-0208: the shared {name} technical identity, seeded at
# Vault path zuno/{name}/technical by ansible/roles/vault/tasks/install.yml.
# Never hardcoded here. Add more `data:` entries here (and matching env
# vars in templates/deployment.yaml) if this integration needs more than
# one credential.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{{{ .Values.credentials.secretName }}}}
  namespace: {{{{ .Values.namespace }}}}
  labels:
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  refreshInterval: {{{{ .Values.credentials.refreshInterval }}}}
  secretStoreRef:
    name: {{{{ .Values.credentials.secretStoreName }}}}
    kind: ClusterSecretStore
  target:
    name: {{{{ .Values.credentials.secretName }}}}
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{{{ .Values.credentials.vaultPath }}}}
        property: token
'''


def _networkpolicy_yaml(name: str) -> str:
    return f"""# {name}-mcp must accept traffic ONLY from the MCP Gateway, not other
# same-namespace pods - same reasoning as every other MCP server chart.
# The app also validates the X-Zuno-Gateway-Token shared secret as
# defense in depth.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {name}-mcp
  namespace: {{{{ .Values.namespace }}}}
  labels:
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {name}-mcp
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mcp-gateway
      ports:
        - protocol: TCP
          port: 8000
"""


def _serviceaccount_yaml(name: str) -> str:
    return f"""# Dedicated, least-privilege service account. No RBAC binding: this
# service only talks to its backend over HTTPS and serves HTTP, never the
# Kubernetes API.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {name}-mcp
  namespace: {{{{ .Values.namespace }}}}
  labels:
    app.kubernetes.io/name: {name}-mcp
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
"""


def _service_yaml(name: str) -> str:
    return f"""apiVersion: v1
kind: Service
metadata:
  name: {name}-mcp
  namespace: {{{{ .Values.namespace }}}}
  labels:
    app.kubernetes.io/name: {name}-mcp
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: {name}-mcp
  ports:
    - name: http
      port: 8000
      targetPort: http
"""


def _helpers_tpl(name: str) -> str:
    return f'''{{{{/*
OpenShift image-change trigger: patches the named container's image field
directly from the ImageStreamTag whenever a fresh Build pushes to it, so
a rebuild rolls this Deployment with no manual pod deletion. Call with
(dict "repository" .Values.image.repository "tag" .Values.image.tag
"container" <container name>). `base` strips the registry+namespace
prefix down to the bare ImageStream name the trigger's `from.name`
expects (the stream itself always lives in zuno-ai-build regardless of
this chart's own namespace).
*/}}}}
{{{{- define "mcp-{name}.imageTrigger" -}}}}
{{{{- list (dict "from" (dict "kind" "ImageStreamTag" "name" (printf "%s:%s" (base .repository) .tag) "namespace" "zuno-ai-build") "fieldPath" (printf "spec.template.spec.containers[?(@.name==\\"%s\\")].image" .container)) | toJson -}}}}
{{{{- end -}}}}
'''


def _app_d0_yaml(name: str) -> str:
    return f"""---
# No Day0 content for mcp-{name}; see gitops/apps/README.md's -d0/-d1
# convention (a stateless MCP server has no schema/prerequisite Job to
# run before its own Deployment).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zuno-mcp-{name}-d0
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-142"
spec:
  project: zuno
  source:
    repoURL: https://github.com/startxfr/zuno-demo.git
    targetRevision: main
    path: gitops/charts/noop
    helm:
      releaseName: zuno-mcp-{name}-d0
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
"""


def _app_d1_yaml(name: str) -> str:
    return f"""---
# The {name} MCP server (ADR-0119 scaffold).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zuno-mcp-{name}-d1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-141"
spec:
  project: zuno
  source:
    repoURL: https://github.com/startxfr/zuno-demo.git
    targetRevision: main
    path: gitops/charts/mcp-{name}
    helm:
      releaseName: zuno-mcp-{name}-d1
  destination:
    server: https://kubernetes.default.svc
    namespace: zuno-ai-run
  ignoreDifferences:
    # image.openshift.io/triggers patches this field directly from the
    # ImageStream whenever a fresh Build completes, so ArgoCD must not
    # treat that patch as drift from the Git-declared tag and revert it.
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
"""


FILES = {
    "components/mcp-servers/{name}/server.py": lambda n, d: _server_py(n, d),
    "components/mcp-servers/{name}/requirements.txt": lambda n, d: _requirements_txt(),
    "components/mcp-servers/{name}/Dockerfile": lambda n, d: _dockerfile(),
    "components/mcp-servers/{name}/README.md": lambda n, d: _readme_md(n, d),
    "components/mcp-servers/{name}/tests/test_mcp_protocol.py": lambda n, d: _test_mcp_protocol_py(n),
    "gitops/charts/mcp-{name}/Chart.yaml": lambda n, d: _chart_yaml(n, d),
    "gitops/charts/mcp-{name}/values.yaml": lambda n, d: _values_yaml(n),
    "gitops/charts/mcp-{name}/templates/deployment.yaml": lambda n, d: _deployment_yaml(n),
    "gitops/charts/mcp-{name}/templates/externalsecret.yaml": lambda n, d: _externalsecret_yaml(n),
    "gitops/charts/mcp-{name}/templates/networkpolicy.yaml": lambda n, d: _networkpolicy_yaml(n),
    "gitops/charts/mcp-{name}/templates/serviceaccount.yaml": lambda n, d: _serviceaccount_yaml(n),
    "gitops/charts/mcp-{name}/templates/service.yaml": lambda n, d: _service_yaml(n),
    "gitops/charts/mcp-{name}/templates/_helpers.tpl": lambda n, d: _helpers_tpl(n),
    "gitops/apps/mcp-{name}/application-d0.yaml": lambda n, d: _app_d0_yaml(n),
    "gitops/apps/mcp-{name}/application-d1.yaml": lambda n, d: _app_d1_yaml(n),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("name", help="server name, lowercase-kebab-case (e.g. git-forge)")
    parser.add_argument("--description", default="TODO: describe this integration", help="one-line description")
    parser.add_argument("--force", action="store_true", help="overwrite existing files (default: refuse)")
    args = parser.parse_args()

    name = args.name
    if name != name.lower() or "_" in name or " " in name:
        print(f"error: name must be lowercase-kebab-case, got {name!r}", file=sys.stderr)
        return 1

    planned = {path_tpl.format(name=name): builder(name, args.description) for path_tpl, builder in FILES.items()}

    if not args.force:
        existing = [p for p in planned if (REPO_ROOT / p).exists()]
        if existing:
            print("refusing to overwrite existing files (pass --force to override):", file=sys.stderr)
            for p in existing:
                print(f"  {p}", file=sys.stderr)
            return 1

    for rel_path, content in planned.items():
        full_path = REPO_ROOT / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)
        print(f"wrote {rel_path}")

    print(
        f"\nScaffolded '{name}'. Next steps:\n"
        f"  1. Replace example_tool in components/mcp-servers/{name}/server.py with real tools.\n"
        f"  2. Add capabilities to platform/bindings/tools/tool-bindings.yaml and policies/tools/tool-policy.yaml.\n"
        f"  3. Add a matrix entry to .github/workflows/build-publish.yml if this server is NOT under "
        f"components/mcp-servers/ with a standard Dockerfile (servers under components/mcp-servers/ are "
        f"discovered automatically, ADR-0119).\n"
        f"  4. Add mcp-{name} to platform/security/check_workload_hardening.py's DEPLOYMENT_CHARTS and "
        f"NetworkPolicy chart lists (python3 platform/supply-chain/check_mcp_server_conformance.py will "
        f"flag this if forgotten).\n"
        f"  5. Add a '{name} MCP server tests' step to .github/workflows/lint.yml's python job.\n"
        f"  6. Seed zuno/{name}/technical in ansible/roles/vault/tasks/install.yml.\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
