apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    zuno.io/managed-by: zuno-ansible
spec:
  provider:
    vault:
      server: "http://vault.zuno-data.svc:8200"
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-reader
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
