#!/usr/bin/env python3
"""ADR-0511/WP-54: the live quota-exceedance proof.

ADR-0511's third acceptance criterion is "a demo user exceeding a request
limit receives an explicit quota error". Everything needed to prove that
has been deployed and `Enforced` since WP-071 unblocked the ext_authz
transport path, but nothing in the repo actually exercised it - `grep -n
429` across evaluations/ and platform/testing/ returned nothing before
this file. This is that missing run, as a repeatable check rather than a
one-off operator command.

What it drives: the `tekos-quota-demo` HTTPRoute
(gitops/charts/connectivity-link/templates/quota-demo-route.yaml), which
carries both an AuthPolicy (Keycloak JWT via Authorino) and the generated
RateLimitPolicy `zuno-quota`
(templates/quota-ratelimitpolicies.yaml, generated by
platform/okf/generate_quota_enforcement.py from policies/quotas/quota-policy.yaml).

Why two bursts and not one: the per-class thresholds are what prove the
policy file's *dimensions* actually reached Limitador, not just that some
rate limit exists. `standard` (no x-zuno-quota-class header) limits a
single `auth.identity.sub` to 60 requests / 5m; `intensive` limits the
same sub to 10 / 5m. Seeing the 429 arrive at ~11 in one burst and ~61 in
the other, with the same token, is the per-dimension keying evidence the
WP's follow-up section asks for - one run, both halves.

The public Route is used deliberately (not an in-cluster Service name):
it is the same hop a demo user takes, and it needs none of the
`app.kubernetes.io/name: acceptance-gate` NetworkPolicy labelling the
in-cluster hops require.

Note on re-runs: Limitador's window here is a 5-minute fixed window, so
two runs inside five minutes share a counter and the second one sees its
429 far earlier than the nominal threshold. That is enforcement working,
not a regression, so a low first-429 index is reported rather than
failed - see _classify() below.

Prints a JSON array of Day2Result rows to stdout, same convention as
day2_stresstest.py and day2_bulk.py.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys
from dataclasses import asdict
from typing import Dict, List, Optional, Tuple

import httpx

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from day2_report import Day2Result, log_test_line  # noqa: E402

AGENT = os.getenv("AGENT", "tekos")
PERSONA = os.getenv("STRESS_TEST_PERSONA", "consultant-01")
QUOTA_TIMEOUT_SECONDS = float(os.getenv("QUOTA_TIMEOUT_SECONDS", "20"))
# The demo Route is served by the cluster's own ingress wildcard, which is
# not publicly trusted: an operator running this from a laptop has no way
# to verify it without the cluster CA in their trust store, while the
# in-cluster Job gets that CA from odh-trusted-ca-bundle. Verification is
# therefore defaulted off so the check is runnable from either side - but
# kept as one named, overridable knob rather than an unexplained literal
# at each call site. Set QUOTA_VERIFY_TLS=1, or to a CA bundle path,
# wherever that trust is actually available.
_verify_env = os.getenv("QUOTA_VERIFY_TLS", "")
VERIFY_TLS = _verify_env if _verify_env.startswith("/") else _verify_env == "1"

# Thresholds mirror policies/quotas/quota-policy.yaml's per-user request
# limits. They are asserted against, not read from, that file on purpose:
# a generator bug that dropped a limit would still pass a check that
# derived its own expectation from the same source it is validating.
STANDARD_USER_LIMIT = int(os.getenv("QUOTA_STANDARD_USER_LIMIT", "60"))
INTENSIVE_USER_LIMIT = int(os.getenv("QUOTA_INTENSIVE_USER_LIMIT", "10"))
# Enough headroom past each limit to see the transition without turning a
# functional check into a load test.
BURST_HEADROOM = int(os.getenv("QUOTA_BURST_HEADROOM", "8"))


def _demo_url() -> str:
    """The quota-demo Route. `demoHostname` in the connectivity-link
    chart's values.yaml is what actually names it in-cluster; this
    reconstructs the same name from whichever base-domain hint the caller
    already has, so the Job template does not need a third env var when it
    already passes FRONTEND_URL.
    """
    explicit = os.getenv("QUOTA_DEMO_URL")
    if explicit:
        return explicit.rstrip("/")
    domain = os.getenv("CLUSTER_BASE_DOMAIN")
    if not domain:
        # FRONTEND_URL is https://<agent>.apps.<base-domain>; drop the
        # leading agent label to recover the base domain.
        import run_scenarios

        host = run_scenarios.FRONTEND_URL.split("://", 1)[-1].split("/", 1)[0]
        domain = host.split(".", 1)[1] if "." in host else host
    return f"https://tekos-quota-demo.{domain}"


def _auth_headers() -> Dict[str, str]:
    # Reuses run_scenarios.py's own ROPC token-fetch helper (mounted
    # alongside this file), same as day2_bulk.py does, instead of
    # duplicating that grant logic.
    #
    # QUOTA_TOKEN overrides it with an already-minted access token. Two
    # reasons that escape hatch exists rather than a second grant
    # implementation: it lets an operator aim this check at any identity
    # (a different persona, or a group whose quota class differs) without
    # that identity needing a confidential client; and run_scenarios'
    # helper calls httpx with default TLS verification, which cannot
    # succeed from outside the cluster while Keycloak is served by the
    # ingress wildcard - httpx resolves trust through certifi and ignores
    # SSL_CERT_FILE, so there is no environment-only way around it. The
    # in-cluster Job, which has the CA from odh-trusted-ca-bundle, takes
    # the normal path and needs none of this.
    token = os.getenv("QUOTA_TOKEN")
    if token:
        return {"Authorization": f"Bearer {token}"}

    import run_scenarios

    return run_scenarios.auth_headers(PERSONA)


def _burst(
    url: str,
    headers: Dict[str, str],
    count: int,
    label: str,
) -> Tuple[Optional[int], List[int], Optional[str]]:
    """Send `count` sequential requests. Returns
    (index of the first 429 or None, all status codes, first 429 body).
    Sequential rather than concurrent: Limitador's counter is shared, so
    concurrency only blurs which request crossed the threshold.
    """
    statuses: List[int] = []
    first_429: Optional[int] = None
    first_429_body: Optional[str] = None
    with httpx.Client(timeout=QUOTA_TIMEOUT_SECONDS, verify=VERIFY_TLS, follow_redirects=False) as client:
        for i in range(count):
            try:
                resp = client.get(url, headers=headers)
                status = resp.status_code
            except Exception as exc:  # noqa: BLE001 - a transport error is a datapoint, not a crash
                log_test_line(AGENT, "quota", f"{label}-{i}", f"request {i + 1}/{count}", False, f"error: {exc}")
                statuses.append(0)
                continue
            statuses.append(status)
            if status == 429 and first_429 is None:
                first_429 = i
                first_429_body = (resp.text or "")[:200]
            log_test_line(
                AGENT, "quota", f"{label}-{i}", f"request {i + 1}/{count}",
                status < 500, f"status={status}",
            )
    return first_429, statuses, first_429_body


def _classify(label: str, first_429: Optional[int], limit: int, statuses: List[int]) -> Day2Result:
    """A 429 anywhere proves enforcement. Where it landed relative to the
    policy's limit is reported but not failed on, because a re-run inside
    the same 5-minute fixed window legitimately starts with the counter
    already part-consumed.
    """
    sent = len(statuses)
    if first_429 is None:
        return Day2Result(
            AGENT, "quota", f"{label}-429", "quota", False,
            f"no 429 in {sent} requests (limit={limit}/5m, statuses={sorted(set(statuses))}) status=0",
        )
    # Nominal boundary: request index `limit` is the first one over.
    note = "at the policy boundary"
    if first_429 < limit:
        note = "earlier than the nominal boundary - 5m window part-consumed by a prior run"
    elif first_429 > limit:
        note = "later than the nominal boundary"
    return Day2Result(
        AGENT, "quota", f"{label}-429", "quota", True,
        f"first 429 at request {first_429 + 1}/{sent} (limit={limit}/5m, {note}) status=429",
    )


def run() -> List[Day2Result]:
    if AGENT != "tekos":
        return [Day2Result(
            AGENT, "quota", "n/a", "coverage", True,
            "the ADR-0511 quota-demo Route is Tekos-only today",
        )]

    url = _demo_url()
    results: List[Day2Result] = []

    # 1. Auth is still the gate in front of the counter. Without this, a
    #    blanket 429 from a misconfigured policy would look like a pass.
    try:
        with httpx.Client(timeout=QUOTA_TIMEOUT_SECONDS, verify=VERIFY_TLS) as client:
            anon = client.get(url).status_code
    except Exception as exc:  # noqa: BLE001
        anon = 0
        log_test_line(AGENT, "quota", "anon", "unauthenticated request", False, f"error: {exc}")
    results.append(Day2Result(
        AGENT, "quota", "auth-enforced", "security", anon == 401,
        f"unauthenticated request status={anon} (expected 401)",
    ))

    headers = _auth_headers()

    # 2. intensive first: 10/5m, so it costs ~18 requests to prove.
    intensive_headers = dict(headers, **{"x-zuno-quota-class": "intensive"})
    i_first, i_statuses, i_body = _burst(
        url, intensive_headers, INTENSIVE_USER_LIMIT + BURST_HEADROOM, "intensive",
    )
    results.append(_classify("intensive", i_first, INTENSIVE_USER_LIMIT, i_statuses))

    # 3. standard: no class header at all (absent => standard, per the
    #    policy file's documented default), 60/5m.
    s_first, s_statuses, s_body = _burst(
        url, headers, STANDARD_USER_LIMIT + BURST_HEADROOM, "standard",
    )
    results.append(_classify("standard", s_first, STANDARD_USER_LIMIT, s_statuses))

    # 4. The two classes must not share a threshold - that is the
    #    per-dimension keying evidence, and it is the half a single-burst
    #    test cannot produce.
    if i_first is not None and s_first is not None:
        distinct = i_first < s_first
        detail = (
            f"intensive 429 at {i_first + 1}, standard 429 at {s_first + 1} - "
            f"{'distinct per-class counters' if distinct else 'classes did not differentiate'}"
        )
    else:
        distinct = False
        detail = "one or both classes never returned 429; cannot compare thresholds"
    results.append(Day2Result(AGENT, "quota", "class-differentiation", "quota", distinct, detail))

    # 5. No 5xx anywhere. WP-071's whole retraction hinged on 500-vs-401,
    #    so a silent regression back to 500 must fail this check loudly.
    server_errors = [s for s in i_statuses + s_statuses if s >= 500]
    results.append(Day2Result(
        AGENT, "quota", "no-server-error", "quota", not server_errors,
        f"{len(server_errors)} 5xx across {len(i_statuses) + len(s_statuses)} requests"
        + (f" (first status={server_errors[0]})" if server_errors else ""),
    ))

    body = i_body or s_body
    if body is not None:
        log_test_line(AGENT, "quota", "429-body", "quota error body", True, body.replace("\n", " ")[:120])

    return results


def main() -> int:
    results = run()
    print(json.dumps([asdict(r) for r in results]))
    return 0 if all(r.passed for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
