{{- if .Values.subscription.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
  labels:
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: {{ .Values.istioSubscription.channel | quote }}
  name: {{ .Values.istioSubscription.name | quote }}
  source: {{ .Values.istioSubscription.source | quote }}
  sourceNamespace: {{ .Values.istioSubscription.sourceNamespace | quote }}
  startingCSV: {{ .Values.istioSubscription.startingCSV | quote }}
  installPlanApproval: Automatic
{{- end }}
