apiVersion: v2
name: cert-manager
description: Deploys the cert-manager operator (Red Hat build) and a Vault-backed ClusterIssuer.
type: application
version: 0.2.0
dependencies:
  - name: cluster-certmanager
    version: "21.3.277"
    repository: "alias:startx"
