{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: zuno-telemetry
  labels:
    zuno.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
{{- end }}
