FROM registry.access.redhat.com/ubi9/python-311:latest
USER 0
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -f /tmp/requirements.txt
USER 1001
WORKDIR /opt/app-root/src
ENTRYPOINT ["python"]
