apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zuno-data
configMapGenerator:
  - name: zuno-sxa-schema
    files:
      - 001_init.sql=../../../../../data/sxa/schema/001_init.sql
      - 002_pgvector.sql=../../../../../data/sxa/schema/002_pgvector.sql
      - seed.sql=../../../../../data/sxa/fixtures/seed.sql
generatorOptions:
  disableNameSuffixHash: true
  labels:
    zuno.io/managed-by: zuno-ansible
